#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

import os
import glob
env=Environment(CPPPATH = ['..'],
                CXXFLAGS = '-W -Wall -g -Werror -Wno-unused-parameter -O2 -DASTYLE_LIB')
env.StaticLibrary('astyle',Glob('*.cc') + Glob('*.cpp'))

test_env = env.Clone()
test_env.Append(LIBPATH = ['.'])
# test_env.Append(LIBPATH = ['.','../common/'])
test_env.Append(LIBS = ['astyle',
                        # 'common',
                        # 'rt',
                        'pthread'])

for cc in glob.glob('test/*.cc'):
    test_env.Program(os.path.splitext(cc)[0] + '.exe', [cc])
